FROM rockylinux:9

SHELL [ "/bin/bash" , "-c" ]

EXPOSE 1194/udp

ARG SERVERNAME

ENV SERVERNAME=${SERVERNAME}

RUN dnf update -y && \
    dnf install -y epel-release && \
    dnf install -y openvpn && \
    dnf install -y easy-rsa && \
    dnf install -y firewalld

# 인증서 설정 start
RUN mkdir /etc/openvpn/easy-rsa && \
    ln -s /usr/share/easy-rsa /etc/openvpn/easy-rsa
    
# OpenVPN 서버의 CA(인증기관) 인증서 생성
WORKDIR /etc/openvpn/easy-rsa
RUN ./easy-rsa/3/easyrsa init-pki && \
    # default "Easy-RSA CA" 로 인증서 생성 | 비밀번호 없는 CA 인증서 생성
    echo "" | ./easy-rsa/3/easyrsa build-ca nopass && \
    echo "" | ./easy-rsa/3/easyrsa gen-req server nopass && \
    echo "yes" | ./easy-rsa/3/easyrsa sign-req server server && \
    ./easy-rsa/3/easyrsa gen-dh

WORKDIR /etc/openvpn
RUN cp /usr/share/doc/openvpn/sample/sample-config-files/server.conf ./ &&\
    # ./easy-rsa/3/easyrsa build-server-full ${SERVERNAME} nopass && \
    sed -i '78s/ca.crt/\/etc\/openvpn\/easy-rsa\/pki\/ca.crt/' ./server.conf && \
    sed -i '79s/server.crt/\/etc\/openvpn\/easy-rsa\/pki\/issued\/server.crt/' ./server.conf && \
    sed -i '80s/server.key/\/etc\/openvpn\/easy-rsa\/pki\/private\/server.key/' ./server.conf && \
    sed -i '85d' ./server.conf && \
    sed -i '85i dh /etc/openvpn/easy-rsa/pki/dh.pem' ./server.conf && \
    sed -i '244s/tls-auth ta.key/#tls-auth ta.key/' ./server.conf && \
    sed -i '252s/AES-256-CBC/AES-256-GCM/' ./server.conf
# 인증서 설정 end

# firewalld 설정 : 실제 서버의 방화벽에서 openvpn 포트 열기

# IP 포워딩 활성화(영구)
RUN echo "sysctl -w net.ipv4.ip_forward=1" >> /etc/sysctl.conf

# foreground 모드로 실행
CMD ["openvpn", "/etc/openvpn/server.conf"]