version: "3.8"

services:
  webdav:
    build: 
      context: .
      dockerfile: ./Dockerfile_webdav
    container_name: webdav
    ports:
      - "8080:80"
    volumes:
      - /e/Media:/var/www/html/webdav
    env_file:
      - info.env
  
  openvpn:
    build: 
      context: .
      dockerfile: ./Dockerfile_vpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "1194:1194/udp"
    volumes:
      - ./openvpn:/home/openvpn
    env_file:
      - info.env
  
  ddns:
    build: 
      context: .
      dockerfile: ./Dockerfile_ddns
    container_name: ddns
    env_file:
      - info.env