version: "3.8"

services:
  webdav:
    build: 
      conetext: .
      dockerfile: ./Dockerfile_webdav
    container_name: webdav
    ports:
      - "8080:80"
    volumes:
      - /e/Media:/var/www/html/webdav
    env_file:
      - info.env
  
  VPN:
    build: 
      context: .
      dockerfile: ./Dockerfile_vpn
    container_name: vpn
    ports:
      - "1194:1194/udp"
    env_file:
      - info.env