FROM rockylinux:9

SHELL [ "/bin/bash", "-c" ]

COPY no-ip-master.sh /no-ip-master.sh
COPY no-ip.sh /usr/local/src/no-ip.sh

ARG NOIPADDRESS
ARG NOIPPASSWORD

ENV NOIPADDRESS=${NOIPADDRESS}
ENV NOIPPASSWORD=${NOIPPASSWORD}

RUN dnf -y update && \
    dnf install -y wget gcc make && \
    dnf install -y expect

# no-ip2 설치
WORKDIR /usr/local/src
RUN wget http://www.no-ip.com/client/linux/noip-duc-linux.tar.gz && \
    tar -xzf noip-duc-linux.tar.gz && \
    rm -f noip-duc-linux.tar.gz && \
    chmod +x ./no-ip.sh

ENTRYPOINT ["/no-ip-master.sh"]